import type { Metadata } from "next";
import "./globals.css";
import HeroTop from "@/components/hero-top";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="max-w-6xl mx-auto w-full pt-20 px-4">
          <HeroTop />
          {children}
        </div>
      </body>
    </html>
  );
}
